version: '3.7'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - ${N8N_PORT:-5678}:5678
    environment:
      - TZ=Asia/Manila
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - DB_SQLITE_POOL_SIZE=${DB_SQLITE_POOL_SIZE}
      - N8N_RUNNERS_ENABLED=${N8N_RUNNERS_ENABLED}
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=${N8N_BLOCK_ENV_ACCESS_IN_NODE}
      - N8N_DEFAULT_LOCALE=en-PH
      - GENERIC_TIMEZONE=Asia/Manila
      - NODES_EXCLUDE=""
      - N8N_PROXY_HOPS=1
      - N8N_BLOCK_FILE_ACCESS_TO_N8N_FILES=false
      - N8N_RESTRICT_FILE_ACCESS_TO=""
    volumes:
      - /mnt/n8n:/home/node/.n8n
      - /srv/n8n/repos:/data/repos
    networks:
      - n8n_network
networks:
  n8n_network:
    driver: bridge
